name: MGOITC
main: com.comze_instancelabs.oitc.Main
version: ${minigames.releaseversion}-${minigames.timestamp}
author: [InstanceLabs,mepeisen]
softdepend: [Vault, MinigamesLib]
depend: [MinigamesLib]
loadbefore: [MinigamesLib]
commands:
   oitc:
      description: Main command
      usage: /oitc [action]
      aliases: [mgoitc]
